name: Publish Crate

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27

      - uses: cachix/cachix-action@v14
        with:
          name: naxdy-foss
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Enter devshell
        uses: nicknovitski/nix-develop@v1

      - uses: katyo/publish-crates@v2
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
